name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:

  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run eslint

      - name: Run unit tests
        run: npm run test

      # - name: Install Playwright browsers
      #   run: npx playwright install --with-deps

      # - name: Run E2E tests
      #   run: npm run test:e2e

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

  # deploy:
  #   name: Deploy app
  #   runs-on: ubuntu-latest
  #   needs: [simple_deployment_pipeline, tag_release #   if: ${{ github]
  #   concurrency: deploy-group
  #   if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: superfly/flyctl-actions/setup-flyctl@master
  #       with:
  #         version: latest
  #     - name: Fly.io Deploy
  #       run: flyctl deploy --remote-only
  #       env:
  #         FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  notification:
    name: Notify Discord with curl since actions keep failing due to invalid webhook
    needs: [tag_release]
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Send full Discord embed
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "username": "GitHub Actions with curl",
            "avatar_url": "'"${{ secrets.AVATAR_URL }}"'",
            "content": "Hey <@316911818725392384>",
            "embeds": [
              {
                "title": "Deploy",
                "description": "Build and deploy to GitHub Pages",
                "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                "color": 255,
                "fields": [
                  {
                    "name": "Status",
                    "value": "'"${{ job.status }}"'",
                    "inline": true
                  },
                  {
                    "name": "Branch",
                    "value": "'"${{ github.ref_name }}"'",
                    "inline": true
                  },
                  {
                    "name": "Commit",
                    "value": "[`${{ github.sha }}`](https://github.com/${{ github.repository }}/commit/${{ github.sha }})",
                    "inline": false
                  },
                  {
                    "name": "Triggered by",
                    "value": "'"${{ github.actor }}"'",
                    "inline": true
                  }
                ],
                "image": {
                  "url": "'"${{ secrets.EMBED_IMAGE }}"'"
                }
              }
            ]
          }' ${{ secrets.DISCORD_WEBHOOK }}
