name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:

  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Lint code
        run: npm run eslint
      - name: Run unit tests
        run: npm run test
      # - name: Install Playwright browsers
      #   run: npx playwright install --with-deps
      # - name: Run E2E tests
        # run: npm run test:e2e
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
  # deploy:
  #   name: Deploy app
  #   runs-on: ubuntu-latest
  #   needs: [simple_deployment_pipeline, tag_release]
  #   concurrency: deploy-group             # optional: only one deploy at a time
  #   if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
  #   steps:
  #     # - uses: actions/checkout@v4
  #     # - uses: superfly/flyctl-actions/setup-flyctl@master
  #     #   with:
  #     #     version: latest
  #     # - name: Fly.io Deploy
  #     #   run: flyctl deploy --remote-only
  #     #   env:
  #     #     FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  notification:
    name: notify discord with webhook
    needs: [tag_release]
    runs-on: ubuntu-latest

    steps:
      - name: Notify success
        if: ${{ success() }}
        uses: rjstone/discord-webhook-notify@c2597273488aeda841dd1e891321952b51f7996f
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          username: aDaOne123
          avatarUrl: https://unsplash.com/illustrations/a-cartoon-of-a-man-giving-a-thumbs-up-dqHbENxCaVA
          text: Below this normal-looking message is an embed!
          severity: info
          color: '#00ff00'
          title: Site deployed successfully!
          description: "Deployment succeeded."
          footer: Deployment bot

      - name: Notify failure
        if: ${{ failure() }}
        uses: rjstone/discord-webhook-notify@c2597273488aeda841dd1e891321952b51f7996f
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          username: aDaOne123
          avatarUrl: https://unsplash.com/illustrations/a-cartoon-of-a-man-giving-a-thumbs-up-dqHbENxCaVA
          text: Below this normal-looking message is an embed!
          severity: error
          color: '#ff0000'
          title: Deployment failed
          description: "Something went wrong during deployment."
          footer: Deployment bot
