name: Testing stuff

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"

# the pipeline below is functional

# name: Deployment pipeline

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches: [ main ]
#     types: [ opened, synchronize ]

# jobs:
#   simple_deployment_pipeline:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v4
#         with:
#           node-version: '20'
#       - name: Install dependencies
#         run: npm install
#       - name: Linting
#         run: npm run eslint

#   notify_success:
#     needs: simple_deployment_pipeline
#     runs-on: ubuntu-latest
#     if: ${{ success() }}
#     steps:
#       - name: Notify Success
#         uses: sarisia/actions-status-discord@v1
#         with:
#           webhook: ${{ secrets.DISCORD_WEBHOOK }}
#           status: ${{ job.status }}
#           content: "Hey adaone123<@316911818725392384>"
#           title: "Deploy"
#           description: "Build and deploy to GitHub Pages"
#           color: 0x0000ff
#           url: "https://github.com/sarisia/actions-status-discord"
#           username: "GitHub Actions"

#   notify_failure:
#     needs: simple_deployment_pipeline
#     runs-on: ubuntu-latest
#     if: ${{ failure() }}
#     steps:
#       - name: Notify Failure
#         uses: sarisia/actions-status-discord@v1
#         with:
#           webhook: ${{ secrets.DISCORD_WEBHOOK }}
#           status: ${{ job.status }}
#           content: "Hey <@316911818725392384>"
#           title: "Deployment Failed"
#           description: "The deployment encountered an error."
#           color: 0xff0000
#           url: "https://github.com/sarisia/actions-status-discord"
#           username: "GitHub Actions"
